<div class="timeline-pubbox-container">
    <div class="lp">
        <div class="avatar">
            <img src="<?php echo($me['avatar']); ?>" alt="Avatar">
        </div>
    </div>
    <div class="rp">
        <form class="form">
            <div class="input-holder">
                <div class="rateit" id="rate_post_input" data-rateit-step="1" data-rateit-mode="font" style="font-size: 50px;"></div>
                <span id="rate_val">0</span>
                <input type="hidden" id="hidden-post-id"/>
            </div>
            <div class="post-privacy-holder">
                <div class="post-privacy-holder_rp">
                    <button class="btn-custom md main-inline" id="submit-rate-post" type="button">
                        <?php echo cl_translate("Like it"); ?>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
