<div style="background: #fff; border-radius: 5px; border:1px solid rgb(230, 236, 240); padding: 30px 50px;">
	<h3 style="padding: 0px; margin: 0 0 15px 0; font-size: 24px; line-height: 24px; color: #14171a;">
		<?php echo cl_translate("Hello"); ?>: <b><?php echo($cl['email_data']["name"]); ?></b>,
	</h3>
	<p style="padding: 0; margin: 0 0 30px 0; font-size: 16px; color: #14171a;">
		<?php echo cl_translate("Here is your activation code for your account ({@code_val@}), copy it, open the link below, then on the account activation page, paste the code into the field and click the registration confirmation button!", array('code_val' => $cl['email_data']['code'])); ?>
	</p>
	<p style="font-size: 12px; color: #5b7083;">
		<span>
			{%config name%} - <?php echo cl_translate("Support team"); ?>.
		</span>
	</p>
</div>